#pragma once
#include "windows.h"

HMODULE MustLoadLibrary(const wchar_t* libName);


#define _SHGetSpecialFolderPathA SHGetSpecialFolderPathA
long __stdcall __InterlockedIncrement(
	long volatile *lpAddend);
LONG __stdcall __InterlockedExchange(
	LONG volatile *Target,
	LONG Value);
long __stdcall __InterlockedDecrement(
	long volatile *lpAddend);

class ZImports
{
public:
	static void LoadImports();
	static inline void *_CreateFileA = nullptr;
	static inline void *_WriteFile = nullptr;
	static inline void *_GetCurrentProcessId = nullptr;
	static inline void *_FindWindowA = nullptr;
	static inline void *_socket = nullptr;
	static inline void *_Sleep = nullptr;
	static inline void *___AhnHS_CheckHackShieldRunningStatus = nullptr;
	static inline void *___AhnHS_PreTranslateBufferedDIMessage = nullptr;
	static inline void *_CloseHandle = nullptr;
	static inline void *_AdjustWindowRect = nullptr;
	static inline void *_GetSystemDirectoryA = nullptr;
	static inline void *_OffsetRect = nullptr;
	static inline void *_RegEnumKeyExA = nullptr;
	static inline void *_AIL_quick_status = nullptr;
	static inline void *_lstrcpyA = nullptr;
	static inline void *_VirtualAllocEx = nullptr;
	static inline void *_RtlUnwind = nullptr;
	static inline void *_HttpSendRequestA = nullptr;
	static inline void *___AhnHS_HSUpdateA = nullptr;
	static inline void *_SafeArrayDestroy = nullptr;
	static inline void *_getpeername = nullptr;
	static inline void *_Process32First = nullptr;
	static inline void *_ExitProcess = nullptr;
	static inline void *_ijlWrite = nullptr;
	static inline void *_WaitForSingleObject = nullptr;
	static inline void *_GetSystemTimeAsFileTime = nullptr;
	static inline void *_ijlInit = nullptr;
	static inline void *_GetWindowTextA = nullptr;
	static inline void *_IsBadWritePtr = nullptr;
	static inline void *_wsprintfA = nullptr;
	static inline void *_GetOEMCP = nullptr;
	static inline void *_OpenProcess = nullptr;
	static inline void *_OpenProcessToken = nullptr;
	static inline void *_GetDlgItem = nullptr;
	static inline void *_AIL_quick_set_volume = nullptr;
	static inline void *_CharUpperBuffA = nullptr;
	static inline void *_HttpOpenRequestA = nullptr;
	static inline void *___AhnHS_IsModuleSecureW = nullptr;
	static inline void *_TlsSetValue = nullptr;
	static inline void *_AIL_quick_load_mem = nullptr;
	static inline void *_LeaveCriticalSection = nullptr;
	static inline void *_ijlRead = nullptr;
	static inline void *_SelectObject = nullptr;
	static inline void *_DeleteObject = nullptr;
	static inline void *_GetVersionExA = nullptr;
	static inline void *_MoveWindow = nullptr;
	static inline void *_closesocket = nullptr;
	static inline void *_RegDeleteValueA = nullptr;
	static inline void *_VerQueryValueA = nullptr;
	static inline void *___AhnHS_InitializeA = nullptr;
	static inline void *_CreateEventA = nullptr;
	static inline void *_GetCurrentProcess = nullptr;
	static inline void *_BringWindowToTop = nullptr;
	static inline void *___AhnHS_CheckFileCRCW = nullptr;
	static inline void *_AttachThreadInput = nullptr;
	static inline void *_SetLastError = nullptr;
	static inline void *_NMCO_MemoryFree = nullptr;
	static inline void *___AhnHS_MakeResponse = nullptr;
	static inline void *_GetVersion = nullptr;
	static inline void *_WriteConsoleA = nullptr;
	static inline void *_NMCO_SetPatchOption = nullptr;
	static inline void *_InternetConnectA = nullptr;
	static inline void *_CreateProcessA = nullptr;
	static inline void *_htonl = nullptr;
	static inline void *_MessageBoxA = nullptr;
	static inline void *_AIL_quick_ms_length = nullptr;
	static inline void *_IsBadReadPtr = nullptr;
	static inline void *_NMCO_CallNMFunc = nullptr;
	static inline void *_SetEvent = nullptr;
	static inline void *_InterlockedIncrement = nullptr;
	static inline void *_UnmapViewOfFile = nullptr;
	static inline void *_DirectInput8Create = nullptr;
	static inline void *_SetUnhandledExceptionFilter = nullptr;
	static inline void *_InterlockedDecrement = nullptr;
	static inline void *_SystemTimeToFileTime = nullptr;
	static inline void *_AIL_quick_startup = nullptr;
	static inline void *_InitializeCriticalSectionAndSpinCount = nullptr;
	static inline void *___AhnHS_MakeGuidAckMsg = nullptr;
	static inline void *_WriteConsoleW = nullptr;
	static inline void *___AhnHS_StartMonitorW = nullptr;
	static inline void *_GetModuleHandleA = nullptr;
	static inline void *_LCMapStringW = nullptr;
	static inline void *___AhnHS_SaveFuncAddress = nullptr;
	static inline void *_LoadLibraryA = nullptr;
	static inline void *___AhnHS_SetUserIdW = nullptr;
	static inline void *_RegQueryValueExA = nullptr;
	static inline void *_Netbios = nullptr;
	static inline void *_InternetOpenA = nullptr;
	static inline void *_DispatchMessageA = nullptr;
	static inline void *_GetProcessMemoryInfo = nullptr;
	static inline void *_CoCreateGuid = nullptr;
	static inline void *___AhnHS_Uninitialize = nullptr;
	static inline void *_LocalAlloc = nullptr;
	static inline void *_IsValidCodePage = nullptr;
	static inline void *_SafeArrayCreate = nullptr;
	static inline void *___AhnHS_CheckAPIHookedW = nullptr;
	static inline void *_NMCO_SetLocaleAndRegion = nullptr;
	static inline void *_MapViewOfFile = nullptr;
	static inline void *_CreateDIBSection = nullptr;
	static inline void *_RegFlushKey = nullptr;
	static inline void *_GetStdHandle = nullptr;
	static inline void *_GetFileVersionInfoSizeA = nullptr;
	static inline void *_getsockname = nullptr;
	static inline void *_FileTimeToSystemTime = nullptr;
	static inline void *_HeapCreate = nullptr;
	static inline void *_FreeLibrary = nullptr;
	static inline void *___AhnHS_PauseService = nullptr;
	static inline void *_GetStringTypeA = nullptr;
	static inline void *_GetTickCount = nullptr;
	static inline void *_GetConsoleCP = nullptr;
	static inline void *_RegSetValueExA = nullptr;
	static inline void *_RegQueryInfoKeyA = nullptr;
	static inline void *_Thread32First = nullptr;
	static inline void *___AhnHS_PreTranslateImmediateDIMessage = nullptr;
	static inline void *_TerminateProcess = nullptr;
	static inline void *_SetStdHandle = nullptr;
	static inline void *_GetEnvironmentStrings = nullptr;
	static inline void *_GetAdaptersInfo = nullptr;
	static inline void *_OpenMutexA = nullptr;
	static inline void *_GetWindowThreadProcessId = nullptr;
	static inline void *_VariantClear = nullptr;
	static inline void *_ijlFree = nullptr;
	static inline void *_Module32Next = nullptr;
	static inline void *___AhnHS_Direct3DCreate9 = nullptr;
	static inline void *_FreeEnvironmentStringsA = nullptr;
	static inline void *___AhnHS_CheckAPIHookedA = nullptr;
	static inline void *_HeapSize = nullptr;
	static inline void *_ExitThread = nullptr;
	static inline void *_GetFileSize = nullptr;
	static inline void *_Process32Next = nullptr;
	static inline void *_inet_addr = nullptr;
	static inline void *_IsDBCSLeadByte = nullptr;
	static inline void *_CreateThread = nullptr;
	static inline void *_CharNextA = nullptr;
	static inline void *_CreateMutexA = nullptr;
	static inline void *_LookupPrivilegeValueA = nullptr;
	static inline void *_CreateCompatibleDC = nullptr;
	static inline void *___AhnHS_SendHsLogA = nullptr;
	static inline void *_VirtualFree = nullptr;
	static inline void *_GetWindow = nullptr;
	static inline void *_QueryPerformanceCounter = nullptr;
	static inline void *_WSACleanup = nullptr;
	static inline void *___AhnHS_StopService = nullptr;
	static inline void *___AhnHS_Direct3DCreate8 = nullptr;
	static inline void *___AhnHS_InitializeW = nullptr;
	static inline void *_VirtualQuery = nullptr;
	static inline void *_InternetCloseHandle = nullptr;
	static inline void *_GetFileVersionInfoA = nullptr;
	static inline void *_LCMapStringA = nullptr;
	static inline void *_TlsGetValue = nullptr;
	static inline void *_GetStartupInfoA = nullptr;
	static inline void *_MultiByteToWideChar = nullptr;
	static inline void *_VirtualAlloc = nullptr;
	static inline void *_IsDebuggerPresent = nullptr;
	static inline void *_RegCloseKey = nullptr;
	static inline void *_MapVirtualKeyA = nullptr;
	static inline void *_FreeEnvironmentStringsW = nullptr;
	static inline void *_RaiseException = nullptr;
	static inline void *_GetCommandLineA = nullptr;
	static inline void *_FormatMessageA = nullptr;
	static inline void *_TlsFree = nullptr;
	static inline void *_RegCreateKeyExA = nullptr;
	static inline void *_GetModuleFileNameA = nullptr;
	static inline void *___AhnHS_SetUserIdA = nullptr;
	static inline void *_VariantCopy = nullptr;
	static inline void *_CreateWindowExA = nullptr;
	static inline void *___AhnHS_IsModuleSecureA = nullptr;
	static inline void *_PtInRect = nullptr;
	static inline void *___AhnHS_HSUpdateExW = nullptr;
	static inline void *___AhnHS_VerifyProtectedFunction = nullptr;
	static inline void *_SetFilePointer = nullptr;
	static inline void *_UnhandledExceptionFilter = nullptr;
	static inline void *_GetLocaleInfoA = nullptr;
	static inline void *___AhnHS_StartService = nullptr;
	static inline void *_lstrcmpA = nullptr;
	static inline void *_GetWindowsDirectoryA = nullptr;
	static inline void *_TlsAlloc = nullptr;
	static inline void *___AhnHS_PreTranslateBufferedDICounter = nullptr;
	static inline void *___AhnHS_CheckFileCRCA = nullptr;
	static inline void *_FindNextFileA = nullptr;
	static inline void *_AIL_quick_unload = nullptr;
	static inline void *_LocalFree = nullptr;
	static inline void *_AIL_quick_shutdown = nullptr;
	static inline void *_GetEnvironmentStringsW = nullptr;
	static inline void *_IsWindowEnabled = nullptr;
	static inline void *_SetRectEmpty = nullptr;
	static inline void *_GetTempPathA = nullptr;
	static inline void *_GetObjectA = nullptr;
	static inline void *_GetCurrentThreadId = nullptr;
	static inline void *___AhnHS_ResumeService = nullptr;
	static inline void *_WSAGetLastError = nullptr;
	static inline void *_ReadFile = nullptr;
	static inline void *_AdjustTokenPrivileges = nullptr;
	static inline void *_WriteProcessMemory = nullptr;
	static inline void *_Module32First = nullptr;
	static inline void *_GetCPInfo = nullptr;
	static inline void *_FlushFileBuffers = nullptr;
	static inline void *_BitBlt = nullptr;
	static inline void *_GetStringTypeW = nullptr;
	static inline void *___AhnHS_StartMonitorA = nullptr;
	static inline void *_DeleteFileA = nullptr;
	static inline void *_GetLastError = nullptr;
	static inline void *_CopyFileA = nullptr;
	static inline void *_VariantInit = nullptr;
	static inline void *_wvsprintfA = nullptr;
	static inline void *_RegEnumValueA = nullptr;
	static inline void *___AhnHS_HSUpdateExA = nullptr;
	static inline void *_htons = nullptr;
	static inline void *_SetHandleCount = nullptr;
	static inline void *___AhnHS_sendto = nullptr;
	static inline void *_EnterCriticalSection = nullptr;
	static inline void *_RegOpenKeyExA = nullptr;
	static inline void *_HeapReAlloc = nullptr;
	static inline void *_AIL_quick_ms_position = nullptr;
	static inline void *_PeekMessageA = nullptr;
	static inline void *_DeleteCriticalSection = nullptr;
	static inline void *___AhnHS_HSUpdateW = nullptr;
	static inline void *_TranslateMessage = nullptr;
	static inline void *_VirtualProtect = nullptr;
	static inline void *_GetProcAddress = nullptr;
	static inline void *_GlobalMemoryStatus = nullptr;
	static inline void *_DeleteDC = nullptr;
	static inline void *_GetConsoleOutputCP = nullptr;
	static inline void *___AhnHS_MakeAckMsg = nullptr;
	static inline void *_GetLocalTime = nullptr;
	static inline void *_AIL_set_redist_directory = nullptr;
	static inline void *_HeapFree = nullptr;
	static inline void *_RegDeleteKeyA = nullptr;
	static inline void *_GetProcessHeap = nullptr;
	static inline void *_gethostbyname = nullptr;
	static inline void *_InterlockedExchange = nullptr;
	static inline void *_FindClose = nullptr;
	static inline void *___AhnHS_SendHsLogW = nullptr;
	static inline void *_SetRect = nullptr;
	static inline void *_AIL_quick_set_ms_position = nullptr;
	static inline void *_GetConsoleMode = nullptr;
	static inline void *_lstrlenA = nullptr;
	static inline void *_CompareFileTime = nullptr;
	static inline void *_LoadStringA = nullptr;
	static inline void *_ReleaseMutex = nullptr;
	static inline void *_GetExitCodeProcess = nullptr;
	static inline void *_InitializeCriticalSection = nullptr;
	static inline void *_FindFirstFileA = nullptr;
	static inline void *_LoadBitmapA = nullptr;
	static inline void *_Thread32Next = nullptr;
	static inline void *_GetErrorInfo = nullptr;
	static inline void *_CreateFileMappingA = nullptr;
	static inline void *_WSAStartup = nullptr;
	static inline void *_GetFileType = nullptr;
	static inline void *_HeapAlloc = nullptr;
	static inline void *_AIL_quick_halt = nullptr;
	static inline void *_lstrcpynA = nullptr;
	static inline void *_VariantChangeType = nullptr;
	static inline void *_GetTempFileNameA = nullptr;
	static inline void *_GetVolumeInformationA = nullptr;
	static inline void *_InternetSetStatusCallback = nullptr;
	static inline void *_lstrcmpiA = nullptr;
	static inline void *_SendMessageA = nullptr;
	static inline void *_VirtualProtectEx = nullptr;
	static inline void *_ReadProcessMemory = nullptr;
	static inline void *___AhnHS_GetSDKVersion = nullptr;
	static inline void *_timeGetTime = nullptr;
	static inline void *_LoadLibraryExA = nullptr;
	static inline void *_AIL_quick_play = nullptr;
	static inline void *_GetModuleHandleW = nullptr;
	static inline void *_DialogBoxParamA = nullptr;
	static inline void *_EnableWindow = nullptr;
	static inline void *_EnumThreadWindows = nullptr;
	static inline void *_GetACP = nullptr;
	static inline void *_CreateToolhelp32Snapshot = nullptr;
	static inline void *_WideCharToMultiByte = nullptr;

	static inline void *__ijlInit = nullptr;  // TODO
	static inline void *__ijlFree = nullptr;  // TODO
	static inline void *__ijlWrite = nullptr; // TODO
	static inline void *__ijlRead = nullptr;  // TODO
};

static void __ijlInit();
static void __ijlFree();
static void __ijlWrite();
static void __ijlRead();


#define _GetAdaptersInfo GetAdaptersInfo
#define _Netbios Netbios

void _DirectInput8Create();