#pragma once
#include "RegenBase.hpp"

#include "InputSystem/InputSystem.hpp"
#include "MapLoadable/MapLoadable.hpp"
#include "UtilDlgEx/UtilDlgEx.hpp"

#include "UIStatusBar/UIStatusBar.hpp"
#include "PortalList/PortalList.hpp"
#include "UIMiniMap/UIMiniMap.hpp"
#include "TrunkDlg/TrunkDlg.hpp"
#include "RPSGameDlg/RPSGameDlg.hpp"
#include "UIMessenger/UIMessenger.hpp"
#include "QuickslotKeyMappedMan/QuickslotKeyMappedMan.hpp"
#include "UserPool/UserPool.hpp"
#include "SummonedPool/SummonedPool.hpp"
#include "MobPool/MobPool.hpp"
#include "NpcPool/NpcPool.hpp"
#include "EmployeePool/EmployeePool.hpp"
#include "DropPool/DropPool.hpp"
#include "MessageBoxPool/MessageBoxPool.hpp"
#include "AffectedAreaPool/AffectedAreaPool.hpp"
#include "ReactorPool/ReactorPool.hpp"
#include "FuncKeyMappedMan/FuncKeyMappedMan.hpp"

#include "ScriptMan/ScriptMan.hpp"
#include "ShopDlg/ShopDlg.hpp"
#include "StoreBankDlg/StoreBankDlg.hpp"
#include "MapleTVMan/MapleTVMan.hpp"

#include "BattleRecordMan/BattleRecordMan.hpp"
#include "ExpeditionIntermediary/ExpeditionIntermediary.hpp"
#include "StringPolicy/StringPolicy.hpp"
#include "SoundMan/SoundMan.hpp"
#include "WvsApp/WvsApp.hpp"
#include "Crc32/Crc32.hpp"

#include "CtrlSelector/CtrlSelector.hpp"
#include "Field_CookieHouse/Field_CookieHouse.hpp"
#include "Field_Balrog/Field_Balrog.hpp"
#include "Field_SpaceGAGA/Field_SpaceGAGA.hpp"
#include "Field_SnowBall/Field_SnowBall.hpp"
#include "Field_ContiMove/Field_ContiMove.hpp"
#include "Field_Coconut/Field_Coconut.hpp"
#include "Field_MonsterCarnival/Field_MonsterCarnival.hpp"
#include "Field_Dojang/Field_Dojang.hpp"
#include "Field_AriantArena/Field_AriantArena.hpp"
#include "Field_Wedding/Field_Wedding.hpp"
#include "Field_Tutorial/Field_Tutorial.hpp"
#include "Field_Battlefield/Field_Battlefield.hpp"
#include "Field_Witchtower/Field_Witchtower.hpp"
#include "Field_Massacre/Field_Massacre.hpp"
#include "Field_PartyRaid/Field_PartyRaid.hpp"
#include "Field_NoDragon/Field_NoDragon.hpp"
#include "Field_DynamicFoothold/Field_DynamicFoothold.hpp"
#include "Field_EscortResult/Field_EscortResult.hpp"
#include "Field_HuntingAdballoon/Field_HuntingAdballoon.hpp"
#include "Field_KillCount/Field_KillCount.hpp"
#include "Field_ShowaBath/Field_ShowaBath.hpp"


#include "PartyQuestInfo/PartyQuestInfo.hpp"
#include "QuestMan/QuestMan.hpp"